---
author:
  - 'Stefan Lang StefanLang@med.lu.se'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.50
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: stefans_libs
no_index:
  directory:
    - inc
    - t
requires:
  DBI: 0
  Date::Simple: 0
  GD::SVG: 0
  Number::Format: 0
  Statistics::R: 0
  inc::Module::Install: 0
version: 0.01
