pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/gbFile.pm --outfile=gbFile.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/root.pm --outfile=root.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/designImporter.pm --outfile=designImporter.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/fastaFile.pm --outfile=fastaFile.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/histogram.pm --outfile=histogram.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/importHyb.pm --outfile=importHyb.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/NimbleGene_config.pm --outfile=NimbleGene_config.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/root.pm --outfile=root.html
mkdir database
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/database/antibodyDB.pm --outfile=database/antibodyDB.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/database/array_Hyb.pm --outfile=database/array_Hyb.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/database/cellTypeDB.pm --outfile=database/cellTypeDB.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/database/fileDB.pm --outfile=database/fileDB.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/database/oligo2dnaDB.pm --outfile=database/oligo2dnaDB.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/database/array_GFF.pm --outfile=database/array_GFF.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/database/array_TStat.pm --outfile=database/array_TStat.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/database/designDB.pm --outfile=database/designDB.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/database/hybInfoDB.pm --outfile=database/hybInfoDB.html
mkdir nimbleGeneFiles
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/nimbleGeneFiles/gffFile.pm --outfile=nimbleGeneFiles/gffFile.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/nimbleGeneFiles/ndfFile.pm --outfile=nimbleGeneFiles/ndfFile.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/nimbleGeneFiles/pairFile.pm --outfile=nimbleGeneFiles/pairFile.html
mkdir chromosome_ripper
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/chromosome_ripper/gbFileMerger.pm --outfile=chromosome_ripper/gbFileMerger.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/chromosome_ripper/seq_contig.pm --outfile=chromosome_ripper/seq_contig.html
mkdir evaluation
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/evaluation/GBpict.pm --outfile=evaluation/GBpict.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/evaluation/summaryLine.pm --outfile=evaluation/summaryLine.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/evaluation/evaluateHMM_data.pm --outfile=evaluation/evaluateHMM_data.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/evaluation/plotGFF_Files_HMM.pm --outfile=evaluation/plotGFF_Files_HMM.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/evaluation/tableLine.pm --outfile=evaluation/tableLine.html
mkdir gbFile
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/gbFile/gbFeature.pm --outfile=gbFile/gbFeature.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/gbFile/gbHeader.pm --outfile=gbFile/gbHeader.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/gbFile/gbRegion.pm --outfile=gbFile/gbRegion.html
mkdir statistics
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/statistics/HMM.pm --outfile=statistics/HMM.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/statistics/newGFFtoSignalMap.pm --outfile=statistics/newGFFtoSignalMap.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/statistics/statisticItem.pm --outfile=statistics/statisticItem.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/statistics/MAplot.pm --outfile=statistics/MAplot.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/statistics/statisticItemList.pm --outfile=statistics/statisticItemList.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/statistics/UMS.pm --outfile=statistics/UMS.html
mkdir sequence_modification
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/sequence_modification/blastLine.pm --outfile=sequence_modification/blastLine.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/sequence_modification/imgtFeatureDB.pm --outfile=sequence_modification/imgtFeatureDB.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/sequence_modification/inverseBlastHit.pm --outfile=sequence_modification/inverseBlastHit.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/sequence_modification/blastResult.pm --outfile=sequence_modification/blastResult.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/sequence_modification/imgtFeature.pm --outfile=sequence_modification/imgtFeature.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/sequence_modification/primerList.pm --outfile=sequence_modification/primerList.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/sequence_modification/imgtFile.pm --outfile=sequence_modification/imgtFile.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/sequence_modification/primer.pm --outfile=sequence_modification/primer.html
pod2html --podpath=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/ --podroot=/Mass/IgH-Locus/doc/  --htmldir=/Mass/IgH-Locus/doc/ --infile=/home/stefan/IgH-Locus/Libs_new_structure/stefans_libs/sequence_modification/imgt2gb.pm --outfile=sequence_modification/imgt2gb.html
