#! /usr/bin/perl
#  Copyright (C) 2008 Stefan Lang

#  This program is free software; you can redistribute it 
#  and/or modify it under the terms of the GNU General Public License 
#  as published by the Free Software Foundation; 
#  either version 3 of the License, or (at your option) any later version.

#  This program is distributed in the hope that it will be useful, 
#  but WITHOUT ANY WARRANTY; without even the implied warranty of 
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
#  See the GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License 
#  along with this program; if not, see <http://www.gnu.org/licenses/>.

use strict;
use stefans_libs::sequence_modification::imgtFeatureDB;
use stefans_libs::sequence_modification::imgt2gb;


my ( $imgtFeatureGB, $imgtFile, $features, $FEATURES, $imgt, $imgt2gb );

$imgtFeatureGB = imgtFeatureDB->new();
$imgt2gb = imgt2gb->new();

$FEATURES = {
    "V-EXON"       => 1,
    "C-REGION"     => 1,
    "J-REGION"     => 1,
    "D-REGION"     => 1,
    "CH1"          => 1,
    "CH2"          => 1,
    "CH3"          => 1,
    "CH4"          => 1,
    "CH5"          => 1,
    "CH6"          => 1,
    "CH7"          => 1,
    "CH8"          => 1,
    "CH-S"         => 1,
    "M"            => 1,
    "M1"           => 1,
    "M2"           => 1,
    "V-NONAMER"    => 1,
    "V-HEXAMER"    => 1,
    "J-NONAMER"    => 1,
    "J-HEXAMER"    => 1,
    "EX1"          => 1,
    "EX2"          => 1,
    "EX3"          => 1,
    "EX4"          => 1,
    "exon"         => 1,
    "J_segment"    => 1,
    "D_segment"    => 1,
    "C_segment"    => 1,
    "V_segment"    => 1,
    "L-PART1"      => 1,
    "V-D-J-REGION" => 1,
    "L-PART2"      => 1
};

$imgt = {
    "(DJ)-C-CLUSTER"       => "misc_sequence",
    "(DJ)-J-C-CLUSTER"     => "misc_sequence",
    "(DJ)-J-CLUSTER"       => "misc_sequence",
    "(VDJ)-C-CLUSTER"      => "misc_sequence",
    "(VDJ)-J-C-CLUSTER"    => "misc_sequence",
    "(VDJ)-J-CLUSTER"      => "misc_sequence",
    "(VJ)-C-CLUSTER"       => "misc_sequence",
    "(VJ)-J-C-CLUSTER"     => "misc_sequence",
    "(VJ)-J-CLUSTER"       => "misc_sequence",
    "1st-CYS"              => "misc_sequence",
    "2nd-CYS"              => "misc_sequence",
    "3'D-HEPTAMER"         => "misc_signal",
    "3'D-NONAMER"          => "misc_signal",
    "3'D-RS"               => "misc_signal",
    "3'D-SPACER"           => "misc_sequence",
    "3'UTR"                => "3'UTR",
    "5'D-HEPTAMER"         => "misc_signal",
    "5'D-NONAMER"          => "misc_signal",
    "5'D-RS"               => "misc_signal",
    "5'D-SPACER"           => "misc_signal",
    "ACCEPTOR-SPLICE"      => "misc_signal",
    "C-CLUSTER"            => "gene",
    "C-GENE"               => "gene",
    "C-LIKE-DOMAIN"        => "gene",
    "C-REGION"             => "C_region",
    "C-SEQUENCE"           => "C_region",
    "CAAT_SIGNAL"          => "CAAT_signal",
    "CAP_SITE"             => "misc_sequence",
    "CDR1"                 => "CDR",
    "CDR1-IMGT"            => "CDR",
    "CDR2"                 => "CDR",
    "CDR2-IMGT"            => "CDR",
    "CDR3"                 => "CDR",
    "CDR3-IMGT"            => "CDR",
    "CH-S"                 => "misc_sequence",
    "CH-SD"                => "exon",
    "CH-T"                 => "exon",
    "CH-X"                 => "exon",
    "CH1"                  => "C_region",
    "CH1D"                 => "exon",
    "CH2"                  => "C_region",
    "CH2D"                 => "exon",
    "CH3"                  => "C_region",
    "CH3D"                 => "exon",
    "CH4"                  => "C_region",
    "CH4D"                 => "exon",
    "CH5"                  => "C_region",
    "CH6"                  => "C_region",
    "CH7"                  => "C_region",
    "CL"                   => "exon",
    "CONFLICT"             => "conflict",
    "CONNECTING-REGION"    => "exon",
    "CONSERVED-TRP"        => "misc_sequence",
    "CYTOPLASMIC-REGION"   => "misc_sequence",
    "D-(DJ)-C-CLUSTER"     => "misc_sequence",
    "D-(DJ)-CLUSTER"       => "misc_sequence",
    "D-(DJ)-J-C-CLUSTER"   => "misc_sequence",
    "D-(DJ)-J-CLUSTER"     => "misc_sequence",
    "D-CLUSTER"            => "misc_sequence",
    "D-GENE"               => "D_segment",
    "D-J-C-CLUSTER"        => "misc_sequence",
    "D-J-C-SEQUENCE"       => "misc_sequence",
    "D-J-CLUSTER"          => "misc_sequence",
    "D-J-GENE"             => "misc_sequence",
    "D-J-REGION"           => "misc_sequence",
    "D-J-SEQUENCE"         => "misc_sequence",
    "D-REGION"             => "D_segment",
    "D-SEQUENCE"           => "D_segment",
    "D1-REGION"            => "D_segment",
    "D2-REGION"            => "D_segment",
    "D3-REGION"            => "D_segment",
    "DECAMER"              => "misc_signal",
    "DELETION"             => "misc_recomb",
    "DONOR-SPLICE"         => "misc_signal",
    "DUPLICATION"          => "misc_recomb",
    "ENHANCER"             => "enhancer",
    "EX1"                  => "exon",
    "EX2"                  => "exon",
    "EX2A"                 => "exon",
    "EX2B"                 => "exon",
    "EX2C"                 => "exon",
    "EX2R"                 => "exon",
    "EX2T"                 => "exon",
    "EX3"                  => "exon",
    "EX4"                  => "exon",
    "EXON"                 => "exon",
    "FR1"                  => "misc_sequence",
    "FR1-IMGT"             => "misc_sequence",
    "FR2"                  => "misc_sequence",
    "FR2-IMGT"             => "misc_sequence",
    "FR3"                  => "misc_sequence",
    "FR3-IMGT"             => "misc_sequence",
    "FR4-IMGT"             => "misc_sequence",
    "GENE"                 => "gene",
    "H"                    => "exon",
    "H1"                   => "exon",
    "H2"                   => "exon",
    "H3"                   => "exon",
    "H4"                   => "exon",
    "H5"                   => "exon",
    "HEPTANUCLEOTIDE"      => "misc_signal",
    "HINGE-REGION"         => "exon",
    "I-EXON"               => "exon",
    "INDETERMINATION"      => "unknown",
    "INIT-CODON"           => "misc_sequence",
    "INIT-CONS"            => "misc_sequence",
    "INSERTION"            => "misc_recomb",
    "INT-DONOR-SPLICE"     => "misc_signal",
    "INTERNAL-HEPTAMER"    => "misc_signal",
    "INTRON"               => "intron",
    "J-C-CLUSTER"          => "misc_sequence",
    "J-C-INTRON"           => "misc_sequence",
    "J-C-REGION"           => "misc_sequence",
    "J-C-SEQUENCE"         => "misc_sequence",
    "J-CLUSTER"            => "misc_sequence",
    "J-HEPTAMER"           => "misc_recomb",
    "J-NONAMER"            => "misc_recomb",
    "J-PHE"                => "misc_sequence",
    "J-GENE"               => "J_segment",
    "J-RS"                 => "misc_recomb",
    "J-REGION"             => "J_segment",
    "J-SPACER"             => "misc_recomb",
    "J-TRP"                => "misc_sequence",
    "JUNCTION"             => "misc_sequence",
    "L-INTRON-L"           => "misc_sequence",
    "L-PART1"              => "exon",
    "L-PART2"              => "exon",
    "L-REGION"             => "misc_sequence",
    "L-V-D-J-C-REGION"     => "misc_sequence",
    "L-V-D-J-C-SEQUENCE"   => "misc_sequence",
    "L-V-D-J-REGION"       => "misc_sequence",
    "L-V-D-REGION"         => "misc_sequence",
    "L-V-D-SEQUENCE"       => "misc_sequence",
    "L-V-J-C-REGION"       => "misc_sequence",
    "L-V-J-C-SEQUENCE"     => "misc_sequence",
    "L-V-J-REGION"         => "misc_sequence",
    "L-V-REGION"           => "misc_sequence",
    "L-V-SEQUENCE"         => "misc_sequence",
    "LINKER"               => "misc_sequence",
    "M"                    => "exon",
    "M1"                   => "exon",
    "M2"                   => "exon",
    "MISC_FEATURE"         => "misc_sequence",
    "MISC_RECOMB"          => "misc_recomb",
    "MODIFICATION"         => "variation",
    "MUTATION"             => "variation",
    "N-AND-D-J-REGION"     => "misc_sequence",
    "N-AND-D-REGION"       => "misc_sequence",
    "N-GLYCOSYLATION-SITE" => "misc_sequence",
    "N-REGION"             => "misc_sequence",
    "N1-REGION"            => "misc_sequence",
    "N2-REGION"            => "misc_sequence",
    "N3-REGION"            => "misc_sequence",
    "N4-REGION"            => "misc_sequence",
    "OCTAMER"              => "misc_recomb",
    "P-REGION"             => "misc_sequence",
    "PENTADECAMER"         => "misc_sequence",
    "POLYA_SIGNAL"         => "polyA_signal",
    "POLYA_SITE"           => "polyA_site",
    "PRIMER_BIND"          => "misc_sequence",
    "PYR-RICH"             => "misc_sequence",
    "REPEAT_UNIT"          => "repeat_region",
    "SILENCER"             => "terminator",
    "STERILE-TRANSCRIPT"   => "misc_sequence",
    "STOP-CODON"           => "misc_sequence",
    "SWITCH"               => "misc_recomb",
    "TATA_BOX"             => "TATA_signal",
    "TRANSMEMBRANE-REGION" => "misc_sequence",
    "UNSURE"               => "unsure",
    "UTR"                  => "UTR",
    "V-(DJ)-C-CLUSTER"     => "misc_sequence",
    "V-(DJ)-CLUSTER"       => "misc_sequence",
    "V-(DJ)-J-C-CLUSTER"   => "misc_sequence",
    "V-(DJ)-J-CLUSTER"     => "misc_sequence",
    "V-(VDJ)-C-CLUSTER"    => "misc_sequence",
    "V-(VDJ)-CLUSTER"      => "misc_sequence",
    "V-(VDJ)-J-C-CLUSTER"  => "misc_sequence",
    "V-(VDJ)-J-CLUSTER"    => "misc_sequence",
    "V-(VJ)-C-CLUSTER"     => "misc_sequence",
    "V-(VJ)-CLUSTER"       => "misc_sequence",
    "V-(VJ)-J-C-CLUSTER"   => "misc_sequence",
    "V-(VJ)-J-CLUSTER"     => "misc_sequence",
    "V-CLUSTER"            => "misc_sequence",
    "V-D-(DJ)-C-CLUSTER"   => "misc_sequence",
    "V-D-(DJ)-CLUSTER"     => "misc_sequence",
    "V-D-(DJ)-J-C-CLUSTER" => "misc_sequence",
    "V-D-(DJ)-J-CLUSTER"   => "misc_sequence",
    "V-D-EXON"             => "misc_sequence",
    "V-D-GENE"             => "misc_sequence",
    "V-D-J-C-CLUSTER"      => "misc_sequence",
    "V-D-J-C-REGION"       => "V_segment",
    "V-D-J-CLUSTER"        => "misc_sequence",
    "V-D-J-EXON"           => "misc_sequence",
    "V-D-J-GENE"           => "misc_sequence",
    "V-D-J-REGION"         => "misc_sequence",
    "V-D-REGION"           => "misc_sequence",
    "V-EXON"               => "V_segment",
    "V-GENE"               => "gene",
    "V-HEPTAMER"           => "misc_signal",
    "V-INTRON"             => "intron",
    "V-J-C-CLUSTER"        => "misc_sequence",
    "V-J-C-REGION"         => "misc_sequence",
    "V-J-CLUSTER"          => "misc_sequence",
    "V-J-EXON"             => "misc_sequence",
    "V-J-GENE"             => "misc_sequence",
    "V-J-REGION"           => "misc_sequence",
    "V-LIKE-DOMAIN"        => "misc_sequence",
    "V-NONAMER"            => "misc_signal",
    "V-REGION"             => "V_region",
    "V-RS"                 => "misc_signal",
    "V-SPACER"             => "misc_sequence",
    "VARIATION"            => "variation",
    "scFv"                 => "misc_sequence"
};
$FEATURES = $imgt;

$imgtFile = $imgtFeatureGB->GetIMGT_entry_forACC("AC003057");

$features = $imgtFile->GetFeaturesInRange( 0, 26957, $imgt, $FEATURES );

foreach my $feature (@$features) {
    print  $feature->Print();
}

$features = $imgt2gb->convert_imgtFeatures2gb($features);

foreach my $feature (@$features) {
    print  $feature->getAsGB();
}

print "Fertig!\n";
